# Generated by Django 2.1.2 on 2018-10-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'rpc_Role_Permission',
            },
        ),
        migrations.CreateModel(
            name='RpcApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('url', models.CharField(max_length=100, verbose_name='接口地址')),
                ('desc', models.CharField(max_length=500, verbose_name='接口描述')),
            ],
            options={
                'db_table': 'rpc_api',
            },
        ),
        migrations.CreateModel(
            name='RpcModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('desc', models.CharField(max_length=500, verbose_name='服务描述')),
                ('super_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.RpcModule', verbose_name='父类模块')),
            ],
            options={
                'db_table': 'rpc_module',
            },
        ),
        migrations.CreateModel(
            name='RpcRole',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('desc', models.CharField(max_length=500, verbose_name='角色名称')),
            ],
            options={
                'db_table': 'rpc_Role',
            },
        ),
        migrations.AddField(
            model_name='rpcapi',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.RpcModule', verbose_name='父类模块'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='RpcApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_per', to='app.RpcApi', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='RpcRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_per', to='app.RpcRole', verbose_name='角色'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('RpcRole', 'RpcApi')},
        ),
    ]
