"""
Django settings for script_killing project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

from dramakill import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'databases',
]

LANGUAGE_CODE = settings.LANGUAGE_CODE

TIME_ZONE = settings.TIME_ZONE

USE_I18N = settings.USE_I18N

USE_L10N = settings.USE_L10N

USE_TZ = settings.USE_TZ


STATIC_URL = settings.STATIC_URL

ACTIVEMQ_URL = settings.ACTIVEMQ_URL
ACTIVEMQ_PORT = settings.ACTIVEMQ_PORT
TIME_LINE_QUEUE_NAME = settings.TIME_LINE_QUEUE_NAME
ROLL_OUT_QUEUE_NAME = settings.ROLL_OUT_QUEUE_NAME
TOPIC_NAME = settings.TOPIC_NAME
REDIS_HOST = settings.REDIS_HOST
REDIS_PORT = settings.REDIS_PORT
REDIS_DATABASE = settings.REDIS_DATABASE
DATABASES = settings.DATABASES
WS_PATH = settings.WS_PATH
ZK_PATH = settings.ZK_PATH


